# Generated by Django 4.0.1 on 2022-02-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_store', '0002_alter_product_promo_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
