# Generated by Django 4.0.1 on 2022-03-03 09:04

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_store', '0005_alter_product_colection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('5/ø14mm/US4', '5/ø14mm/US4'), ('6/ø14.3mm/US4+', '6/ø14.3mm/US4+'), ('7/ø14.6mm/', '7/ø14.6mm/'), ('8/ø15mm/US5', '8/ø15mm/US5'), ('9/ø15.3mm', '9/ø15.3mm'), ('10/ø15.6mm/US6-', '10/ø15.6mm/US6-'), ('11/ø16mm/US6', '11/ø16mm/US6'), ('12/ø16.3mm', '12/ø16.3mm'), ('13/ø16.6mm', '13/ø16.6mm'), ('14/ø17mm/US7', '14/ø17mm/US7'), ('15/ø17.3mm', '15/ø17.3mm'), ('16/ø17.6mm/US7+', '16/ø17.6mm/US7+'), ('17/ø18mm/US8', '17/ø18mm/US8'), ('18/ø18.3mm', '18/ø18.3mm'), ('19/ø18.6mm/US9', '19/ø18.6mm/US9'), ('20/ø19mm', '20/ø19mm'), ('21/ø19.3mm/US9+', '21/ø19.3mm/US9+'), ('22/ø19.6mm/US10', '22/ø19.6mm/US10'), ('23/ø20mm', '23/ø20mm'), ('24/ø20.3mm/US11-', '24/ø20.3mm/US11-'), ('25/ø20.6mm/US11', '25/ø20.6mm/US11'), ('26/ø21mm', '26/ø21mm'), ('27/ø21.3/US12', '27/ø21.3/US12'), ('28/ø21.6', '28/ø21.6'), ('29/ø22mm/US13-', '29/ø22mm/US13-'), ('30/ø22.3mm/US13', '30/ø22.3mm/US13'), ('31/ø22.6mm', '31/ø22.6mm'), ('32/ø23mm/US14', '32/ø23mm/US14'), ('33/ø23.3mm', '33/ø23.3mm'), ('34/ø23.6mm', '34/ø23.6mm')], max_length=382, null=True),
        ),
    ]
