# Generated by Django 4.0.1 on 2022-04-05 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_store', '0006_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colection_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='jewelry_store.collection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
